### PR TITLE
Fix unique contraint

### PR DESCRIPTION
**Pull request by dali99**
Possibly add a primary key of type INTEGER rather than using the bridge id for primary?

### CODE REVIEW

**Comment by dhghf** [comment]
I fixed it, the ID is a JSON web token so it'll remain a text type.

**Comment by dali99** [comment]
interesting, any reason room shouldn't be unique?

**Comment by dhghf** [comment]
Well it could be since it always will be

**Comment by dhghf** [comment]
I'll add that now

**Pull request closed without merging**
